### ISSUE TITLE
0.5.2 crashes

### ISSUE THREAD

**Issue by amilopowers** [SMSSecure/SMSSecure#81] opened 2015-04-06 20:32 UTC
Crashes inmidiately after update from 0.5.1. On Nexus 5 with Omnirom (LGE Nexus 5 (omni_hammerhead)).

**Comment by pR0Ps** [comment] 2015-04-06 20:36
This is caused by an oversight that's been fixed as of v0.5.3. Just waiting for the build to propagate out to users.

Your SMS messages are still there and will be accessible again after the update. Sorry about this.

Closing as a duplicate of #61

**Closed by pR0Ps** 2015-04-06 20:36 UTC
