### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AlexAlexandru** [SMSSecure/SMSSecure#143] opened 2015-05-27 17:27 UTC
![image](https://cloud.githubusercontent.com/assets/5292321/7842884/c32cee78-04ae-11e5-9d63-7c1971bb5a7e.png)

**Comment by BastienLQ** [comment] 2015-07-08 08:59
Can you post a full plain text log from the app?

**Comment by pR0Ps** [comment] 2015-07-22 04:09
Closing since this area of the code has changed a lot and I can't reproduce it on the current build. Please make another issue with an updated log (preferably text instead of a screenshot) if you see this crash again.

**Closed by pR0Ps** 2015-07-22 04:09 UTC
