### ISSUE TITLE
Impossible sending muliple persons. 

### ISSUE THREAD

**Issue by Didier83** [SMSSecure/SMSSecure#239] opened 2015-08-31 09:18 UTC
When I choose a contact using the pencil in the right down coin, the application display directly the redaction part to write message, but I have no way to add a new receiver. When I click on the receiver, I have information about him/her, but always no way to add a nex receiver...! I have a Sony Xperia z3 under Lollipop.
Thanks for your help..!!

**Comment by MicroJoe** [comment] 2015-08-31 09:51
You need to create a group before starting a conversation with multiple persons using MMS.

**Comment by BastienLQ** [comment] 2015-08-31 13:53
Duplicate of #130.

**Closed by BastienLQ** 2015-08-31 13:53 UTC
