### ISSUE TITLE
Character counter doesn't work properly since 0.10.0

### ISSUE THREAD

**Issue by frimajnd** [SMSSecure/SMSSecure#279] opened 2015-11-16 05:16 UTC
0.9.0 is the last version in which remaining character counter works properly.

**All versions since show a character limit of 160, no matter if it's secure session or not.**

When secure session is established, character limit per message can't be 160. It's much lower - 63 (or 60?) for the first message and 115 for subsequent ones.

https://github.com/WhisperSystems/Signal-Android/wiki/ProtocolV2  - Sending A Message

0.9.0 - working properly
![working](https://cloud.githubusercontent.com/assets/15865044/11174699/e4fbde9e-8c1f-11e5-9ac3-04d762aa407f.jpg)

0.12.3 - not working properly
![notworking](https://cloud.githubusercontent.com/assets/15865044/11174709/2be52842-8c20-11e5-89e7-4964bced978d.jpg)

It can be pretty annoying if you don't have a plan with unlimited texting and you don't know how many text messages will be sent.

**Comment by discworld** [comment] 2015-11-18 22:57
Looks like a regression added by 5fed681.

**Comment by pR0Ps** [comment] 2015-11-20 05:23
Fixed by c15ad97

**Closed** 2015-11-20 05:23 UTC
