### ISSUE TITLE
sms received both in default messaging service (encrypted format) and in smssecure (cleartext)

### ISSUE THREAD

**Issue by quentinhardy** [SMSSecure/SMSSecure#142] opened 2015-05-25 15:59 UTC
Hello,

I'm using Android **5.0.2**. For information, SMSSecure is **not my default application** for SMS/MMS.

When I receive a SMS encrypted from a SMSSecure contact, the sms is stored **both** in **my default messaging service** (encrypted format) and in **smssecure**(cleartext). Of course, I can't read sms received from this contact in my default messaging service. Consequently, I have 2 notifications when I receive a sms from this contact.

My contact have the same problem with Android **5.1**.

This problem doesn't exist when SMSSecure is my **default** application for SMS/MMS.

Thank you very much in advance,

**Comment by pR0Ps** [comment] 2015-05-25 17:14
Duplicate of #6

**Closed by pR0Ps** 2015-05-25 17:14 UTC

**Comment by Stephane38** [comment] 2015-06-22 08:05
Hello,
I am facing the exact same issue on LG G3. I am not using SMS Secure as my default SMS app and encrypted messages appear both in SMSSEcure (decrypted version) and in standard  SMS app (encrypted copy).
I carefully read the other issue "TextSecure still sees encrypted SMS messages on KitKat+#6" and I do not think it is really a duplicate; I am not using TextSecure; only SMS secure and my default SMS application.
Do you know a way to avoid encrypted messages to appear in the standard SMS app ?
Kind regards, Stephane38

**Comment by pR0Ps** [comment] 2015-06-22 08:39
This is how Android works. When SMSSecure is set as default it receives all messages (and other apps *can* listen for them if they want to - usually not). When another app is set as default it will receive all messages (the encrypted ones too) and SMSSecure listens for them as well.

I'd you don't want your other app to see the encrypted messages, you'll have to set SMSSecure as the default.

**Comment by Stephane38** [comment] 2015-06-23 08:35
Thanks for your answer.
It is really too bad because it works perfectly on my other phone (based on Android 4.4.4).
But I understand you can't do much about it ! It is now how Android works...
