### ISSUE TITLE
Anonymous sender of MMS

### ISSUE THREAD

**Issue by eboulben** [SMSSecure/SMSSecure#214] opened 2015-08-02 16:48 UTC
When in a secured session, sender of mms are not identified
#anonymous is displayed in the dialog, # next to the picture in the conversation.

Version 0.10.1
Build ID: 16e0618

**Comment by BastienLQ** [comment] 2015-08-06 15:55
Duplicate of #67.

**Closed by BastienLQ** 2015-08-06 15:55 UTC
