### ISSUE TITLE
can't open SMSsecure since 0.5.2 update

### ISSUE THREAD

**Issue by KaitoKito** [SMSSecure/SMSSecure#82] opened 2015-04-07 00:05 UTC
Hi,

Thanks for working on this useful app, but I just found a very annoying issue : I updated SMSsecure via Fdroid from 0.5.1 to 0.5.2 and now SMSsecure crash just after I type my password. 
I tried to reinstall the 0.5.1 version which was working fine, but the only way is to uninstall the current version, which will delete all my conversations.

How can I backup the SMS database without opening SMSsecure, and inject it after installing again the 0.5.1 version ? 

Phone specs (if it helps) :
GT i9300 (galaxy S3)
Android 4.2.2 (cyanogen mod 10.1.3)

Friendly,

Kaito.

**Comment by pR0Ps** [comment] 2015-04-07 00:12
We've fixed the issue in the v0.5.3 version, which should be available in F-Droid and other app stores in a few hours.

Unfortunately there's no way to easily back up your messages and reinstall when the app is in this state, but if you don't uninstall, when you get the update, your messages will still be there.

Closing as a duplicate of #61

**Closed by pR0Ps** 2015-04-07 00:12 UTC
