### ISSUE TITLE
Import from SMS app doesn't import MMS

### ISSUE THREAD

**Issue by damienorny** [SMSSecure/SMSSecure#271] opened 2015-11-04 10:43 UTC
I'm using Sony Xperia Z5 on Android 5.1.1 with SMSSecure v0.12.3
I just installed SMSSecure and chose the option to import the already existing SMS database. SMS import is OK but I do not have any MMS message.

**Comment by pR0Ps** [comment] 2015-11-05 00:57
Duplicate of #140

**Closed** 2015-11-05 00:57 UTC
