### ISSUE TITLE
SMSSecure crashes after update from 0.5.1 to 0.5.2

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#74] opened 2015-04-05 22:50 UTC
I built 0.5.1 from source (build ID b1f8fd5) and then upgraded to 0.5.2 also built from source, build ID 76ea14c. After converting the database again, SMSSecure crashes. It might be that my database has become a bit undefined after all those test versions, so for the time being I solved it by removing the program, importing a backup and starting with a fresh DB and see if this holds.

I'll post some snippets of the logfile if it can be relevant: I have more if you need it.

04-06 00:34:14.668 I/ActivityManager(1384): Timeline: Activity_windows_visible id: ActivityRecord{45455710 u0 org.smssecure.smssecure/.DatabaseUpgradeActivity t36} time:15252269
[...]
04-06 00:34:14.988 I/ActivityManager(4515): Timeline: Activity_launch_request id:org.smssecure.smssecure time:15252583
04-06 00:34:14.988 E/AndroidRuntime(4515): FATAL EXCEPTION: pool-1-thread-1
04-06 00:34:14.988 E/AndroidRuntime(4515): Process: org.smssecure.smssecure, PID: 4515
04-06 00:34:14.988 E/AndroidRuntime(4515): java.lang.IllegalArgumentException: No inject registered for members/org.smssecure.smssecure.jobs.CreateSignedPreKeyJob. You must explicitly add it to the 'injects' option in one of your modules.
04-06 00:34:14.988 E/AndroidRuntime(4515): 	at dagger.ObjectGraph$DaggerObjectGraph.getInjectableTypeBinding(ObjectGraph.java:302)
04-06 00:34:14.988 E/AndroidRuntime(4515): 	at dagger.ObjectGraph$DaggerObjectGraph.inject(ObjectGraph.java:279)
04-06 00:34:14.988 E/AndroidRuntime(4515): 	at org.smssecure.smssecure.ApplicationContext.injectDependencies(ApplicationContext.java:67)
04-06 00:34:14.988 E/AndroidRuntime(4515): 	at org.whispersystems.jobqueue.JobManager$1.run(JobManager.java:109)
04-06 00:34:14.988 E/AndroidRuntime(4515): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-06 00:34:14.988 E/AndroidRuntime(4515): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-06 00:34:14.988 E/AndroidRuntime(4515): 	at java.lang.Thread.run(Thread.java:841)
04-06 00:34:14.988 I/ActivityManager(1384): START u0 {cmp=org.smssecure.smssecure/.ConversationListActivity (has extras)} from pid 4515
04-06 00:34:14.998 W/dalvikvm(4515): threadid=22: thread exiting with uncaught exception (group=0x420bcd88)
04-06 00:34:14.998 I/Process (4515): Sending signal. PID: 4515 SIG: 9
04-06 00:34:14.998 D/ActivityManager(1384): New dropbox entry: org.smssecure.smssecure, data_app_crash, 920d2882-44ec-49c7-9e89-d30f8765f04a
04-06 00:34:15.008 I/WindowState(1384): WIN DEATH: Window{43c4c6c8 u0 org.smssecure.smssecure/org.smssecure.smssecure.PassphrasePromptActivity}
04-06 00:34:15.018 I/WindowState(1384): WIN DEATH: Window{450ce8a0 u0 org.smssecure.smssecure/org.smssecure.smssecure.DatabaseUpgradeActivity}
04-06 00:34:15.018 I/ActivityManager(1384): Process org.smssecure.smssecure (pid 4515) has died.
04-06 00:34:15.018 W/ActivityManager(1384): Scheduling restart of crashed service org.smssecure.smssecure/.service.KeyCachingService in 1000ms
04-06 00:34:15.088 I/ActivityManager(1384): Start proc org.smssecure.smssecure for activity org.smssecure.smssecure/.ConversationListActivity: pid=4647 uid=10366 gids={50366, 3003, 1028, 1015, 1023}

**Comment by Rafiot** [comment] 2015-04-06 12:11
I have the same issue. I was using 0.5.1 from F-Droid, updated to 0.5.2 and the app crashes after I enter my passphrase.

**Comment by st7** [comment] 2015-04-06 12:23
Same issue on both of my devices. I used 0.5.1 from F-Droid as well. Keeps crashing after update to 0.5.2.
One device is crashing after entering the password. The other one is not secured with a password. The App without password crashes right away.

**Comment by Rafiot** [comment] 2015-04-06 12:27
same. Reinstalling the app 'solves' the problem (but you lose all the messages).
 
Here are le logs from the time I open the app until it crashes:

```
D/lights  ( 2306): set_light_buttons: 1 D/AudioPolicyManagerBase( 1907): getOutput() device 2, stream 1, samplingRate 0, format 0, channelMask 3, flags 0 D/AudioPolicyManagerBase( 1907): getOutput() returns output 2 D/AudioPolicyManagerBase( 1907): getOutput() device 2, stream 1, samplingRate 0, format 0, channelMask 3, flags 0 D/AudioPolicyManagerBase( 1907): getOutput() returns output 2 D/AudioPolicyManagerBase( 1907): getOutput() device 2, stream 1, samplingRate 48000, format 1, channelMask 3, flags 4 D/AudioPolicyManagerBase( 1907): getOutput() returns output 2 W/AudioTrack( 2306): AUDIO_OUTPUT_FLAG_FAST denied by client due to mismatching sample rate (48000 vs 44100) D/AudioFlinger( 1907): start(4099), calling pid 2306 session 46 D/AudioFlinger( 1907): ? => ACTIVE (4099) on thread 0x40ce5420 D/AudioPolicyManagerBase( 1907): startOutput() output 2, stream 1, session 46 D/audio_hw_primary( 1907): select_output_device: AUDIO_DEVICE_OUT_SPEAKER W/service ( 7216): Broadcasting new secret... W/KeyCachingService( 7216): Starting timeout: 18000000 W/dalvikvm( 7216): threadid=11: thread exiting with uncaught exception (group=0x417c6ce0) E/AndroidRuntime( 7216): FATAL EXCEPTION: pool-1-thread-1 E/AndroidRuntime( 7216): Process: org.smssecure.smssecure, PID: 7216 E/AndroidRuntime( 7216): java.lang.IllegalArgumentException: No inject registered for members/org.smssecure.smssecure.jobs.CreateSignedPreKeyJob. You must explicitly add it to the 'injects' option in on e of your modules. E/AndroidRuntime( 7216):        at dagger.ObjectGraph$DaggerObjectGraph.getInjectableTypeBinding(ObjectGraph.java:302) E/AndroidRuntime( 7216):        at dagger.ObjectGraph$DaggerObjectGraph.inject(ObjectGraph.java:279) E/AndroidRuntime( 7216):        at org.smssecure.smssecure.ApplicationContext.injectDependencies(ApplicationContext.java:67) E/AndroidRuntime( 7216):        at org.whispersystems.jobqueue.persistence.PersistentStorage.injectDependencies(PersistentStorage.java:131) E/AndroidRuntime( 7216):        at org.whispersystems.jobqueue.persistence.PersistentStorage.getJobs(PersistentStorage.java:98) E/AndroidRuntime( 7216):        at org.whispersystems.jobqueue.persistence.PersistentStorage.getAllEncrypted(PersistentStorage.java:77) E/AndroidRuntime( 7216):        at org.whispersystems.jobqueue.JobManager$LoadTask.run(JobManager.java:155) E/AndroidRuntime( 7216):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) E/AndroidRuntime( 7216):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) E/AndroidRuntime( 7216):        at java.lang.Thread.run(Thread.java:841) W/ActivityManager( 2306):   Force finishing activity org.smssecure.smssecure/.PassphrasePromptActivity W/SendReceiveService( 7216): Got a MasterSecret broadcast... W/PartProvider( 7216): Got master secret: org.smssecure.smssecure.crypto.MasterSecret@41ed7488 W/ActivityManager( 2306): Duplicate finish request for ActivityRecord{42a5fd28 u0 org.smssecure.smssecure/.PassphrasePromptActivity t12 f} W/MmsSmsDatabase( 7216): Executing query: SELECT _id, body, read, type, address, address_device_id, subject, thread_id, status, date_sent, date_received, m_type, msg_box, part_count, ct_l, tr_id, m_size , exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched _identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, threa d_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failure s, 'mms' AS transport_type FROM mms WHERE (read = 0) ORDER BY date_received ASC) I/Timeline( 7216): Timeline: Activity_launch_request id:org.smssecure.smssecure time:1305523 I/ActivityManager( 2306): START u0 {cmp=org.smssecure.smssecure/.ConversationListActivity (has extras)} from pid 7216 W/ActivityManager( 2306): Duplicate finish request for ActivityRecord{42641f38 u0 org.smssecure.smssecure/.RoutingActivity t12 f} W/KeyCachingService( 7216): Incrementing activity count...
W/KeyCachingService( 7216): Decrementing activity count...                                                                                                                                       [24/1849]
W/KeyCachingService( 7216): Starting timeout: 18000000
I/dalvikvm( 7216): Could not find method com.melnykov.fab.FloatingActionButton.setElevation, referenced from method com.melnykov.fab.FloatingActionButton.setBackgroundCompat
W/dalvikvm( 7216): VFY: unable to resolve virtual method 29986: Lcom/melnykov/fab/FloatingActionButton;.setElevation (F)V
D/dalvikvm( 7216): VFY: replacing opcode 0x6e at 0x0013
W/dalvikvm( 7216): Unable to resolve superclass of Lcom/melnykov/fab/FloatingActionButton$1; (1562)
W/dalvikvm( 7216): Link of class 'Lcom/melnykov/fab/FloatingActionButton$1;' failed
W/dalvikvm( 7216): Unable to resolve superclass of Lcom/melnykov/fab/FloatingActionButton$1; (1562)
W/dalvikvm( 7216): Link of class 'Lcom/melnykov/fab/FloatingActionButton$1;' failed
W/dalvikvm( 7216): Unable to resolve superclass of Lcom/melnykov/fab/FloatingActionButton$1; (1562)
W/dalvikvm( 7216): Link of class 'Lcom/melnykov/fab/FloatingActionButton$1;' failed
D/dalvikvm( 7216): DexOpt: unable to opt direct call 0x0345 at 0x2a in Lcom/melnykov/fab/FloatingActionButton;.setBackgroundCompat
W/dalvikvm( 7216): Unable to resolve superclass of Lcom/melnykov/fab/FloatingActionButton$1; (1562)
W/dalvikvm( 7216): Link of class 'Lcom/melnykov/fab/FloatingActionButton$1;' failed
D/dalvikvm( 7216): DexOpt: unable to opt direct call 0x74d9 at 0x2f in Lcom/melnykov/fab/FloatingActionButton;.setBackgroundCompat
W/KeyCachingService( 7216): Incrementing activity count...
W/RecipientProvider( 7216): Cache miss [ASYNC]!
W/RecipientProvider( 7216): Cache miss [ASYNC]!
W/RecipientProvider( 7216): Cache miss [ASYNC]!
W/RecipientProvider( 7216): Cache miss [ASYNC]!
W/RecipientProvider( 7216): Cache miss [ASYNC]!
W/RecipientProvider( 7216): Cache miss [ASYNC]!
W/RecipientProvider( 7216): Cache miss [ASYNC]!
W/RecipientProvider( 7216): Cache miss [ASYNC]!
I/ActivityManager( 2306): Displayed org.smssecure.smssecure/.ConversationListActivity: +548ms
I/Timeline( 2306): Timeline: Activity_windows_visible id: ActivityRecord{41cfeae8 u0 org.smssecure.smssecure/.ConversationListActivity t13} time:1306080
I/Timeline( 7216): Timeline: Activity_idle id: android.os.BinderProxy@41bfe478 time:1306518
D/AudioPolicyManagerBase( 1907): getOutput() device 2, stream 1, samplingRate 0, format 0, channelMask 3, flags 0
D/AudioPolicyManagerBase( 1907): getOutput() returns output 2
D/AudioPolicyManagerBase( 1907): getOutput() device 2, stream 1, samplingRate 0, format 0, channelMask 3, flags 0
D/AudioPolicyManagerBase( 1907): getOutput() returns output 2
D/AudioPolicyManagerBase( 1907): getOutput() device 2, stream 1, samplingRate 48000, format 1, channelMask 3, flags 4
D/AudioPolicyManagerBase( 1907): getOutput() returns output 2
W/AudioTrack( 2306): AUDIO_OUTPUT_FLAG_FAST denied by client due to mismatching sample rate (48000 vs 44100)
I/Process ( 7216): Sending signal. PID: 7216 SIG: 9
D/AudioFlinger( 1907): start(4100), calling pid 2306 session 47
D/AudioFlinger( 1907): ? => ACTIVE (4100) on thread 0x40ce9508
D/AudioPolicyManagerBase( 1907): startOutput() output 2, stream 1, session 47
D/audio_hw_primary( 1907): select_output_device: AUDIO_DEVICE_OUT_SPEAKER
I/ActivityManager( 2306): Process org.smssecure.smssecure (pid 7216) has died.
W/ActivityManager( 2306): Scheduling restart of crashed service org.smssecure.smssecure/.service.KeyCachingService in 1000ms
I/WindowState( 2306): WIN DEATH: Window{42695598 u0 org.smssecure.smssecure/org.smssecure.smssecure.ConversationListActivity}
W/ActivityManager( 2306): Force removing ActivityRecord{41cfeae8 u0 org.smssecure.smssecure/.ConversationListActivity t13}: app died, no saved state
W/InputMethodManagerService( 2306): Got RemoteException sending setActive(false) notification to pid 7216 uid 10092
W/Binder  ( 2594): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 2594): java.lang.NullPointerException
W/Binder  ( 2594):      at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
W/Binder  ( 2594):      at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
W/Binder  ( 2594):      at android.os.Binder.execTransact(Binder.java:404)
W/Binder  ( 2594):      at dalvik.system.NativeStart.run(Native Method)
I/Timeline( 2669): Timeline: Activity_idle id: android.os.BinderProxy@41bfc158 time:1309215
I/Timeline( 2306): Timeline: Activity_windows_visible id: ActivityRecord{4242cd38 u0 com.android.launcher3/org.cyanogenmod.trebuchet.CustomHomeLauncher t1} time:1309497
```

**Comment by pR0Ps** [comment] 2015-04-06 12:49
Duplicate of #61 (has been reopened)

**Closed by pR0Ps** 2015-04-06 12:49 UTC
Labels: bug, help wanted
