### ISSUE TITLE
Crash after unlocking database, after updating to 0.5.2, app in unusable state

### ISSUE THREAD

**Issue by tuxayo** [SMSSecure/SMSSecure#79] opened 2015-04-06 15:48 UTC
DB was updated but there is a force close when opening the conversation list.

The app receives SMS but when I want to view them and unlock the DB -> force close.
If I don't close the force close message, I can see the conversations in the background(to have the list in background, I have to manually close the app and lauch it via the Android app manager)
After the app crashed, the new message notification is still here with the message content visible.

Is there something that I can do to recover the messages received since last backup?

Android version: 4.1.2
Number of messages stored: 33100
0.5.1 was the first version installed

**Comment by pR0Ps** [comment] 2015-04-06 15:54
Duplicate of #61

We have a 0.5.3 updating coming out today that corrects this issue. Your messages will be unaffected. Apologies for the inconvenience.

**Closed by pR0Ps** 2015-04-06 15:54 UTC

**Comment by tuxayo** [comment] 2015-04-06 15:58
Here is a logcat:
https://gitlab.com/snippets/4192/raw

**Comment by tuxayo** [comment] 2015-04-06 15:59
Thank for you reactivity, good news it's going to be solved.
If I reinstall TextSecure 2.6.4 to wait the fix, does SMSSecure will still get the new messages?

**Comment by pR0Ps** [comment] 2015-04-06 16:03
SMSSecure will pick up all encrypted messages regardless of if it is set as the default SMS application or not. Regular messages are only picked up if it's set as the default.

**Comment by tuxayo** [comment] 2015-04-06 16:09
So it's not possible to use another SMS app at the same time without preventing SMSSecure to get the regular messages right?
If I build 0.5.3 myself, I could not install it without uninstalling the offical build and lossing the DB if I recall correctly (because of mismatching signature)

**Comment by pR0Ps** [comment] 2015-04-06 16:14
Sorry, I didn't see initially that you're running Jelly Bean. It should be possible for you to use another SMS application in the meantime without impacting SMSSecure.

**Comment by tuxayo** [comment] 2015-04-06 16:29
Tested with AOSP SMS app and TextSecure 2.6.4
The apps can send SMS but only SMSSecure receives them.

I'm in airplane mode waiting F-Droid to build 0.5.3...

**Comment by tuxayo** [comment] 2015-04-06 17:04
> Sorry, I didn't see initially that you're running Jelly Bean

**Comment by tuxayo** [comment] 2015-04-06 17:06
> Sorry, I didn't see initially that you're running Jelly Bean

Does the android version affects the downgrade/mismatching signature problem which constraint us to wait for F-Droid to compile it?
Or is it about the handling of SMS with multiple apps?

**Comment by pR0Ps** [comment] 2015-04-06 17:12
KitKat changed the way having multiple SMS applications on a device worked. The signature verification is the same for both.
