### ISSUE TITLE
Encryption doesn't work at all

### ISSUE THREAD

**Issue by amilopowers** [SMSSecure/SMSSecure#66] opened 2015-04-04 14:57 UTC
I am sorry but the encryption doesn't work on my phone at all. 

I have a Nexus 5 with Omnirom (no Google services).
My friend has a Samsung Galaxy (S4 I guess) with the shipped Android.

We cant exchange the keys. I have no idea why. We both didn't came from Textsecure.

**Comment by amilopowers** [comment] 2015-04-04 15:02
Here is my log: https://gist.github.com/96abd33a1a57b69f300f

**Comment by pR0Ps** [comment] 2015-04-04 15:12
What are you seeing when you try to exchange keys? (Exactly)

**Comment by amilopowers** [comment] 2015-04-04 15:30
That's what I see: https://www.u-cloud.ch/owncloud6/public.php?service=files&t=eeCTp1XazvvF24r

**Comment by amilopowers** [comment] 2015-04-04 15:37
My friend doesn't use Smssecure as his main sms app... Is that mandatory?

**Comment by pR0Ps** [comment] 2015-04-04 16:12
In order to have a secure conversation, both parties must be using SMSSecure. If your friend has it installed, but not set as the main SMS application, then this is a bug, probably related to #47. If he doesn't have it installed, then this is the expected behavior.

Which is your case?

**Comment by amilopowers** [comment] 2015-04-04 16:21
The first. He has installed it but not as default.

We are going to try it again and let you know. Thank you!

**Comment by pR0Ps** [comment] 2015-04-05 16:10
Closing as a duplicate of #47 .

As a workaround, set SMSSecure as the default application, then once the key exchange completes, set it back.

**Closed by pR0Ps** 2015-04-05 16:10 UTC
