### ISSUE TITLE
[Feature request] Encrypted backups for SMS database.

### ISSUE THREAD

**Issue by tuxayo** [SMSSecure/SMSSecure#17] opened 2015-03-22 21:48 UTC

**Comment by BastienLQ** [comment] 2015-03-22 21:51
Duplicate of #16.

**Closed by BastienLQ** 2015-03-22 21:51 UTC
Labels: duplicate

**Comment by tuxayo** [comment] 2015-03-22 22:59
I thought that encryption keys and SMS database could be separated because currently only the database can be exported.
And maybe there are different challenges for the implementation?

**Comment by BastienLQ** [comment] 2015-03-22 23:02
It would be easier to export messages and keys, and users will always be able to remove conversations after the import.
