### ISSUE TITLE
Manual and automatic key exchanges aren't working

### ISSUE THREAD

**Issue by sanjay** [SMSSecure/SMSSecure#129] opened 2015-05-10 13:30 UTC
Seems this is related to bug #32 but it's more extensive.  Just tried to re-setup a connection between a new phone and a phone that was already setup and it isn't working.  Automatic key exchanges aren't working and manual exchanges don't work - clicking on the message does nothing.  This is with the 0.7.0 release.  Seems something was recently broken - this worked before.

**Comment by BastienLQ** [comment] 2015-05-11 13:00
I can't reproduce this bug. Can you provide a log and details about your phones?

**Comment by sanjay** [comment] 2015-05-11 17:42
Not sure if it matters but this is on a Fire Phone.  When I hit click the message to process the encryption key it doesn't do a thing.

**Comment by sanjay** [comment] 2015-05-11 17:43
How do I grab the log file?

**Comment by pR0Ps** [comment] 2015-05-11 17:48
To submit a log go to Settings -> Advanced -> Submit log file, and paste the URL it gives here. Since it only shows the last few minutes of activity, try to take a log file immediately after seeing the problem.

To clarify, you receive an incoming key exchange message, you tap the message, it shows the changed key warning, you tap OK on the warning, and the result is that it doesn't send?

If you have automatic key exchanges turned off, this is a known problem (see #32). However, if automatic key exchanges are turned on, this should work and is a different bug.

**Comment by sanjay** [comment] 2015-05-11 22:33
https://gist.github.com/0032854083e9dd902e66

The phone gets an incoming exchange.  "Complete key exchanges" is selected in settings.  The phone gets a "Received key exchange message, click to process".  The key is NOT automatically processed.  When you click it, the screen goes black then white and then returns to the list of text messages (and not the conversation anymore).  The key isn't processed though.

This happens on a Fire Phone but another phone (Samsung S3 running Cyanogenmod 10.1) works fine.

**Comment by pR0Ps** [comment] 2015-05-12 00:40
Looking at the log, the problem is that the app actually crashes when tapping the message. This crash is an issue with the Android AppCompat library and has been fixed as of [this commit](https://github.com/SMSSecure/SMSSecure/commit/c9a337099fd11c1d9bba668a772d7577d0212cc2).

We've pushed v0.8.0 which includes the fix, it should be available shortly.

If you still see this issue with v0.8.0, reopen it with an updated log and we'll take another look.

**Closed by pR0Ps** 2015-05-12 00:40 UTC
Labels: bug
