### ISSUE TITLE
Incoming secured MMS has no Sender 

### ISSUE THREAD

**Issue by vdveer** [SMSSecure/SMSSecure#224] opened 2015-08-19 16:48 UTC
When TelephoneManager.getLine1Number has no  value,  and no verified phonenumber in SMSSecurePreference is available (I am guessing always since it is not required in this TextSecure fork), the PduComposer for the MMS message will not put a PduHeader.FROM value in the encrypted pdu. This leads to an anonymous incoming message (but since the encapsulated pdu will supply a correct value it will be saved with the correct threadid). 

I have tried to check the MMSDownloadJob and fix the PduHeader value if empty to copy the header from the original pdu, but it doesn't seem to work. Probably I am not reading the code right, so if someone can hint a solution (if it is indeed I bug) I would be more than happy to help.

**Comment by BastienLQ** [comment] 2015-08-19 19:11
Duplicate of #67.

**Closed by BastienLQ** 2015-08-19 19:11 UTC
