### ISSUE TITLE
Option to revert back to old contact icon

### ISSUE THREAD

**Issue by juanito003** [SMSSecure/SMSSecure#152] opened 2015-06-08 07:51 UTC
Would it be possible in Settings->Appearance (or somewhere else) to have all the same contact icon like before 0.8.0? (Like in the capture below, or the android default icon)
Some people find it really disturbing to see all this funky colors, some others find it useful.

Screenshot of an old textsecure:
![textsecure](https://cloud.githubusercontent.com/assets/487038/8030039/a3bc6d5c-0dc3-11e5-8976-395881528384.png)

**Comment by pR0Ps** [comment] 2015-06-08 14:11
Duplicate of #133

**Closed by pR0Ps** 2015-06-08 14:11 UTC
